Feature/registration
agri-gaia/DataDashboard pull request #12
Opened 2023-08-01 06:46 UTC by Julian-Marco

## What this PR changes/adds

_Briefly describe WHAT your pr changes, which features it adds/modifies._

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2023-08-29 08:58 UTC, marcelruland requested changes

2023-08-29 08:58 UTC, marcelruland commented on src/modules/app/app-routing.module.ts
>  export const routes: Routes = [
So muss man bei jeder Route explizit `canActivate: [AuthGuard]` setzen, das kann potentiell vergessen werden. Folgende Variante ist sicherer:

```typescript
const routes: Routes = [
    { path: '', canActivate: [AuthGuard], children: [
      { path : '', component: ComponentA },
      { path : 'add', component : ComponentB },
      { path : ':id', component: ComponentC, canActivate: [] },
    ]}
];
```

Leere Parent-Route, alle children haben einen AuthGuard, der kann mit `[]` explizit deaktiviert werden.

2023-08-29 08:58 UTC, marcelruland commented on src/assets/silent-check-sso.html
> +</html>
EOL missing

2023-08-29 08:58 UTC, marcelruland commented on src/modules/app/app.module.ts
> +    {provide: BACKEND_URL, useValue: environment.backendUrl},
Beide felder `backendUrl` und `apiKey` existieren nicht in `environment.ts` und `environment.prod.ts`.

2023-08-29 08:58 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.html
> +      <ng-container *ngFor="let route of routes.slice(0, routes.length - 2)">
Das bricht zusammen, wenn die Reihenfolge der Routen in `app-routing.module.ts` je geaendert wird. Du kannst den Routen einen data parameter geben und daran filtern.

Logik gehoert auch in `.ts` files, nicht `.html` files.

2023-08-29 08:58 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.html
> +<mat-sidenav-container class="sidenav-container" *ngIf="this.authenticationService.isAuthenticated$ | async; else startPageTemplate">
`authenticationService` bitte `private` lassen und nicht in html files aufrufen.

2023-08-29 08:58 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +  constructor(public authenticationService: AuthenticationService) {}
`private`, nicht `public`

2023-08-29 08:58 UTC, marcelruland commented on src/modules/app/components/registration/registration.component.scss
> + }
EOL fehlt

2023-08-29 08:58 UTC, marcelruland commented on src/modules/app/components/registration/registration.component.ts
> +}
EOL fehlt

2023-08-29 08:58 UTC, marcelruland commented on src/modules/app/components/startpage/startpage.component.html
> +  </div>
EOL fehlt

2023-08-29 08:58 UTC, marcelruland commented on src/modules/app/components/startpage/startpage.component.scss
> + }
EOL fehlt

2023-08-29 09:16 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.html
> +<mat-sidenav-container class="sidenav-container" *ngIf="this.authenticationService.isAuthenticated$ | async; else startPageTemplate">
Das ist die Konstruktion, die Enis vorgeschlagen hatte. Das hat den Sinn, dass der Benutzer die Menüleiste auf der linken Seite erst dann sieht, wenn dieser eingeloggt ist. Ist natürlich hacky, aber vermutlich die leichteste Variante, wenn man nicht übermäßig viel umstellen will.

2023-08-29 09:19 UTC, Julian-Marco commented on src/modules/app/app.module.ts
> +    {provide: BACKEND_URL, useValue: environment.backendUrl},
Sie existieren in unseren lokalen environment-Dateien.

2023-08-29 09:33 UTC, Julian-Marco commented on src/modules/app/components/startpage/startpage.component.scss
> + }
https://github.com/agri-gaia/DataDashboard/pull/12/commits/dd4f9becfeefff3d345045fdbb2be2c1a605d783

2023-08-29 09:33 UTC, Julian-Marco commented on src/modules/app/components/startpage/startpage.component.html
> +  </div>
https://github.com/agri-gaia/DataDashboard/pull/12/commits/dd4f9becfeefff3d345045fdbb2be2c1a605d783

2023-08-29 09:33 UTC, Julian-Marco commented on src/modules/app/components/registration/registration.component.ts
> +}
https://github.com/agri-gaia/DataDashboard/pull/12/commits/dd4f9becfeefff3d345045fdbb2be2c1a605d783

2023-08-29 09:33 UTC, Julian-Marco commented on src/modules/app/components/registration/registration.component.scss
> + }
https://github.com/agri-gaia/DataDashboard/pull/12/commits/dd4f9becfeefff3d345045fdbb2be2c1a605d783

2023-08-29 09:33 UTC, Julian-Marco commented on src/assets/silent-check-sso.html
> +</html>
https://github.com/agri-gaia/DataDashboard/pull/12/commits/dd4f9becfeefff3d345045fdbb2be2c1a605d783

2023-08-29 09:34 UTC, Julian-Marco commented on src/modules/app/components/startpage/startpage.component.html
> +  </div>
https://github.com/agri-gaia/DataDashboard/pull/12/commits/dd4f9becfeefff3d345045fdbb2be2c1a605d783

2023-08-29 10:31 UTC, Julian-Marco commented on src/modules/app/app-routing.module.ts
>  export const routes: Routes = [
Hmm, die leere Route (und damit die Standard-Seite) ist hier aber explizit die Startpage, die ja eben gerade keinen Auth Guard haben soll.

2023-08-29 12:52 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.html
> +      <ng-container *ngFor="let route of routes.slice(0, routes.length - 2)">
Habe es mal mit einem protectedRoutes-Array probiert, das nur diejenigen Routen enthält, die hinter dem AuthGuard liegen. https://github.com/agri-gaia/DataDashboard/pull/12/commits/cbc034a5124a641f7661851fb08595b3d95fe466 Dann sollte die Reihenfolge keine Rolle mehr spielen. 

Welche Logik würdest du ins .ts-file packen? 

Edit: Slicing hatte ich verpeilt rauszunehmen: https://github.com/agri-gaia/DataDashboard/pull/12/commits/efa578a1a970170e3c8f122b4fca4bb03dbd8339

2023-08-30 10:31 UTC, marcelruland commented on src/modules/app/app-routing.module.ts
>  export const routes: Routes = [
Dass sollte trotzdem funktionieren wenn du ne child route mit `path: '', canActivate: []` setzt. Falls nicht, wuerde ich die Startseite auf `path: 'index'` setzen und die leere Route auf /index umleiten lassen.

2023-09-12 06:54 UTC, marcelruland requested changes

2023-09-12 06:54 UTC, marcelruland commented on src/modules/app/app-routing.module.ts
>  export const routes: Routes = [
Das hier ist das einzige, was noch gemacht werden muss.

2023-09-12 11:59 UTC, Julian-Marco commented on src/modules/app/app-routing.module.ts
>  export const routes: Routes = [
https://github.com/agri-gaia/DataDashboard/pull/12/commits/b6b06bc33eba3858565c9d24f1b66d37d275bccb

2023-09-13 05:29 UTC, marcelruland approved these changes

2023-09-13 05:55 UTC, merged