Feature/58533 keycloak
agri-gaia/DataDashboard pull request #6
Opened 2023-05-16 07:53 UTC by Julian-Marco

## What this PR changes/adds

_Briefly describe WHAT your pr changes, which features it adds/modifies._

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2023-05-23 06:32 UTC, marcelruland requested changes

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
Asynchrone Operationen gehoeren nicht in einen Konstruktor.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +      this.profile = userProfile
Du schreibst das userProfile in die class property, **danach** schaust du ob es null ist.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +    this.authenticationService.userProfile$.pipe(take(1)).subscribe(profile => (this.profile = profile));
Hier machst du jetzt dasselbe was du im Konstruktor schon gemacht hast nochmal, allerdings ohne null check.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +    if (this.profile?.group === 'LMIS') {
Das braucht ein `enum` und ein `switch`, dass alle Values abdeckt. Also grob so:

```Typescript
enum Organisation {
  Hsos,
  Lmis,
  AgBrain
}

getGroupLogoFilePath(orga: Organisation) {
  let logoDir = "/assets/theme/company-logos/"
  switch (orga) {
    case Organisation.Hsos:
      return logoDir + "hsos.svg"
      break;
    case Organisation.Lmis:
      return logoDir + "lmis.svg"
      break;
    case Organisation.AgBrain:
      return logoDir + "agbrain.svg"
      break;
    default:
      throw new Error("Could not determine groupLogoPath.");
  }
}
```

Das `UserProfile` interface braucht ein Feld `organisation: Organisation`.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/core/authentication/authentication.service.ts
> +interface DecodedToken {
Bis auf den `preferred_username` ist dieses Interface identisch mit dem `UserProfile` Interface (dort heisst es `username`). Wofuer ist das?

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/app.module.ts
> +        url: 'https://account.platform.agri-gaia.com',
Die Werte sollten ins `environment.ts` bzw `environment.prod.ts`.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/app.module.ts
> +          '/clients/public']
Du hast hier Routen aus der keycloak-angular Dokumentation gecopypastet, die es bei uns ueberhaupt nicht gibt.

`bearerExcludedUrls` bewirkt, dass diese Routen ohne token angesprochen werden, das macht fuer uns keinen Sinn.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/core/authentication/authentication.service.ts
> +                const decodedToken = jwt_decode<DecodedToken>(token);
Das JWT wird hier erst in das `DecodedToken` interface gepackt und dann direkt anschliessend in das `UserProfile` interface. Das ist redundant.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.html
> +<!--  <mat-form-field class="form-field" color="accent" id="form-field-destination">
Das Entfernen der Storage Options gehoert nicht auf einen Keycloak-Branch und war nicht geplant.

Zombie Code bitte loeschen.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-demo/pages/catalog-browser/asset-details/asset-details.component.ts
> +      this.url = userProfile!.url;
Redundante non-null assertion.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-demo/pages/catalog-browser/asset-details/asset-details.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
Asynchrone Operationen gehoeren nicht in einen Konstruktor.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
Asynchrone Operationen gehoeren nicht in einen Konstruktor.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-demo/pages/contract-viewer/contract-viewer.component.ts
> +        this.dataConnectorUrl = userProfile!.dataConnectorUrl;
Redundante non-null assertion.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-demo/pages/frame/context-switcher/context-switcher.component.ts
>    platformForm = new FormControl();
Ungenutztes Feld, bitte loeschen. Auf sowas weisst der Linter hin.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-demo/pages/contract-viewer/contract-viewer.component.ts
> +      this.authenticationService.userProfile$.subscribe(userProfile => {
Das `userProfile` ist ein `Observable<UserProfile | null>`, wodurch du immer und immer wieder subscriben musst. Es sollte einfach `UserProfile | null` sein.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.ts
> +interface StorageOption {
Wenn wir keine StorageOptions mehr haben brauchen wir auch kein neues Interface fuer StorageOptions. Wird nur als Parametertyp in einer Methode verwendet, die aber selbst nicht verwendet wird.

2023-05-23 06:32 UTC, marcelruland commented on src/assets/silent-check-sso.html
> +</html>
new line am Ende des files fehlt

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/app.module.ts
> +      bearerExcludedUrls: [
Hier copypastest du Routen aus der keycloak-angular Dokumentation, die es bei uns garnicht gibt. `bearerExcludedUrls` nimmt eine Liste von Routen bei denen dann kein JWT mitgeschickt wird. Das macht fuer uns keinen Sinn.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
Asynchrone Operationen gehoeren nicht in einen Konstruktor.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +      this.profile = userProfile
Du schreibst den Wert in die class property, **danach** schaust du ob er evtl null war.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +    this.authenticationService.userProfile$.pipe(take(1)).subscribe(profile => (this.profile = profile));
Hier machst du jetzt dasselbe was du schon im Konstruktor gemacht hast nochmal, allerdings ohne null check.

2023-05-23 06:32 UTC, marcelruland commented on src/assets/theme/company-logos/lmis-ag-logo-ohne-slogan-default.svg
Assets bitte alle einheitlich benennen.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +    if (this.profile?.group === 'LMIS') {
Alle Zugriffe auf `this.profile.group` werden hier nur durchgefuehrt, wenn `this.profile` nicht null ist. Da der Wert aber asynchron im Konstruktor reingeschrieben wird ist das alles andere als sicher (ist aber so oder so keine gute Herangehensweise).

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/components/navigation/navigation.component.ts
> +  getGroupLogoSource(): string {
Die Methode braucht ein `enum` und ein `switch` um alle Faelle abzudecken. Also grob so:


```TypeScript
enum Organisation {
  Hsos,
  Lmis,
  AgBrain,
}

getGroupLogoFilePath(orga: Organisation): string {
  let logoDir: string = "/assets/theme/company-logos"
  switch (orga) {
    case Organisation.Hsos:
      return logoDir + "/hsos.svg"
    case Organisation.Lmis:
      return logoDir + "/lmis.svg"
    case Organisation.AgBrain:
      return logoDir + "/agbrain.svg"
  }
}
```

Den orga String aus dem JWT mappt man dann direkt auf das enum und schmeisst nen Error wenn kein passender Wert gefunden wird.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/app/app-config.service.ts
Diese Klasse wird noch vom EdcContextService importiert, Import bitte entfernen. VSCode weisst auf solche Probleme unter "Problems" hin.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-demo/pages/frame/context-switcher/context-switcher.component.html
Bitte komplette Komponente inkl ts und css files und directory loeschen, nicht nur das html file.

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-dmgmt-client/variables.ts
> +
Warum entfernt?

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-dmgmt-client/api/policy.service.ts
> -      if (typeof this.configuration.basePath !== 'string') {
Warum entfernt?

2023-05-23 06:32 UTC, marcelruland commented on src/modules/edc-dmgmt-client/api/transferProcess.service.ts
> -                @Inject(CONNECTOR_DATAMANAGEMENT_API) basePath: string,
Ich versteh allgemein nicht ganz was hier mit der connector datamanagement api passiert ist.

2023-05-30 10:02 UTC, Julian-Marco commented on src/modules/app/core/authentication/authentication.service.ts
> +interface DecodedToken {
Ist wieder entfernt, userProfile wird stattdessen verwendet.

2023-05-30 10:05 UTC, Julian-Marco commented on src/modules/app/core/authentication/authentication.service.ts
> +                const decodedToken = jwt_decode<DecodedToken>(token);
DecodedToken Interface ist entfernt, userProfile wird stattdessen verwendet.

2023-05-30 10:08 UTC, Julian-Marco commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.html
> +<!--  <mat-form-field class="form-field" color="accent" id="form-field-destination">
Naja, die Storage Options waren vorher Teil der Konfigurationsdateien aus dem Backend. Da nun lediglich die storageURL aus den Keycloak-Attributen des Benutzers ausgelesen wird, ist es hier nicht mehr relevant. Gehört daher für mich schon dazu.

2023-05-30 10:10 UTC, Julian-Marco commented on src/modules/app/app.module.ts
> +      bearerExcludedUrls: [
Ist entfernt: https://github.com/agri-gaia/DataDashboard/pull/6/commits/932adae28e06d32e268bd4002328c9175614716c

2023-05-30 10:11 UTC, Julian-Marco commented on src/modules/app/app.module.ts
> +          '/clients/public']
Ist entfernt: https://github.com/agri-gaia/DataDashboard/pull/6/commits/932adae28e06d32e268bd4002328c9175614716c

2023-05-30 10:11 UTC, Julian-Marco commented on src/modules/app/core/authentication/authentication.service.ts
> +                const decodedToken = jwt_decode<DecodedToken>(token);
https://github.com/agri-gaia/DataDashboard/pull/6/commits/e1c1b5347696bbfd58d5f45a73150b5b7840cf05

2023-05-30 10:14 UTC, Julian-Marco commented on src/modules/edc-dmgmt-client/api/policy.service.ts
> -      if (typeof this.configuration.basePath !== 'string') {
Eigentlich ist alles, was irgendwie mit irgendeiner configuration zu tun hat, ziemlich redundant, glaube ich. Leider weiß ich auch nicht, was davon aus dem ursprünglichen repo kommt und was irgendwie damals von Enis angepasst worden ist. Glaube ich wollte da einfach etwas aufräumen.

2023-05-30 10:18 UTC, Julian-Marco commented on src/modules/edc-dmgmt-client/api/transferProcess.service.ts
> -                @Inject(CONNECTOR_DATAMANAGEMENT_API) basePath: string,
Die kam vorher aus der AppConfigService, die es ja jetzt nicht mehr gibt, weswegen das Fehlermeldungen geschmissen hat. Vergleiche: https://github.com/agri-gaia/DataDashboard/blob/main/src/modules/app/app.module.ts Hier bin ich leider wieder überfragt, ob es das Ding schon vorher gab oder ob das eine Eigenkreation gewesen ist. Also ja, ziemliches Durcheinander.

2023-05-30 10:19 UTC, Julian-Marco commented on src/modules/edc-dmgmt-client/variables.ts
> +
Siehe anderer Kommentar.

2023-05-30 10:24 UTC, Julian-Marco commented on src/modules/edc-demo/pages/frame/context-switcher/context-switcher.component.html
Das zerschießt mir leider das komplette Repo, deswegen hatte ich es erstmal so gelassen. Der context-switcher war afaik auch schon vorher da, auch wenn er von Enis dann etwas anders verwendet worden ist. Daher ist der tief im Rest des Repos verwurzelt und ich wollte das nicht weiter anfassen, da der Rest unabhängig davon funktioniert.

2023-05-30 10:26 UTC, Julian-Marco commented on src/modules/app/app-config.service.ts
Gibt es doch gar nicht mehr. Welchen import meinst du? Die Klasse taucht bei zumindest bei mir nirgends mehr auf.

2023-05-30 10:54 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.ts
> +    if (this.profile?.group === 'LMIS') {
Done. https://github.com/agri-gaia/DataDashboard/pull/6/commits/59b4cbf2426daf0b28962d73a52d42f9ce021b89 https://github.com/agri-gaia/DataDashboard/pull/6/commits/0fd464ebb1b77636b07b9ec26aa6afa4d34c126d das feld gibt es schon, heißt "group".

2023-05-30 10:56 UTC, Julian-Marco commented on src/modules/edc-demo/pages/frame/context-switcher/context-switcher.component.ts
>    platformForm = new FormControl();
Woher kommt das? Steht bei mir im Code gar nicht drin.

2023-05-30 11:02 UTC, Julian-Marco commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.ts
> +interface StorageOption {
Ist raus: https://github.com/agri-gaia/DataDashboard/pull/6/commits/6903f0ca2726674fc16dde42f0da31ccbcc190b6

2023-05-30 11:05 UTC, Julian-Marco commented on src/assets/silent-check-sso.html
> +</html>
Wird aktuell eh nicht verwendet, hab's einfach gelöscht: https://github.com/agri-gaia/DataDashboard/pull/6/commits/7f0a0e6821b89bfeece65987196bc612c43f898f

2023-05-30 11:05 UTC, Julian-Marco commented on src/assets/theme/company-logos/lmis-ag-logo-ohne-slogan-default.svg
Done.

2023-05-30 11:06 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.ts
> +  getGroupLogoSource(): string {
Done.

2023-05-30 11:13 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
Done. https://github.com/agri-gaia/DataDashboard/pull/6/commits/6f9ee0b5cd18437cc72d5037ebb7ffb55d395a6b

2023-05-30 11:13 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.ts
> +      this.profile = userProfile
Fixed. https://github.com/agri-gaia/DataDashboard/pull/6/commits/6f9ee0b5cd18437cc72d5037ebb7ffb55d395a6b

2023-05-30 11:14 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.ts
> +    this.authenticationService.userProfile$.pipe(take(1)).subscribe(profile => (this.profile = profile));
Fixed. https://github.com/agri-gaia/DataDashboard/pull/6/commits/6f9ee0b5cd18437cc72d5037ebb7ffb55d395a6b

2023-05-30 11:46 UTC, Julian-Marco commented on src/modules/edc-demo/pages/catalog-browser/asset-details/asset-details.component.ts
> +      this.url = userProfile!.url;
Fixed. https://github.com/agri-gaia/DataDashboard/pull/6/commits/2823679307ce2edbbce4fb7daa050b79d50a6ade

2023-05-30 11:49 UTC, Julian-Marco commented on src/modules/edc-demo/pages/contract-viewer/contract-viewer.component.ts
> +        this.dataConnectorUrl = userProfile!.dataConnectorUrl;
Fixed. https://github.com/agri-gaia/DataDashboard/pull/6/commits/107753695802d9f44fcb1e9de0813e22a4bd2f8e

2023-05-30 11:51 UTC, Julian-Marco commented on src/modules/app/app.module.ts
> +        url: 'https://account.platform.agri-gaia.com',
Ist die analoge Frage zum richtigen Deployment mit dem api key und der backend url als envs. Leider aktuell noch keinen sinnvollen Ansatz dafür, würde man wohl in dieselbe configMap schreiben müssen (falls das überhaupt sinnvoll ist das bei ner Angular Application zu machen).

2023-05-30 11:55 UTC, Julian-Marco commented on src/modules/edc-demo/pages/catalog-browser/asset-details/asset-details.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
Fixed. https://github.com/agri-gaia/DataDashboard/pull/6/commits/de3ca5f7ef3fcd5d68f51946c877e0565e9adb19

2023-05-30 11:57 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.ts
> +    this.authenticationService.userProfile$.pipe(take(1)).subscribe(profile => (this.profile = profile));
Fixed. https://github.com/agri-gaia/DataDashboard/pull/6/commits/6f9ee0b5cd18437cc72d5037ebb7ffb55d395a6b

2023-05-30 11:58 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.ts
> +    if (this.profile?.group === 'LMIS') {
Fixed? https://github.com/agri-gaia/DataDashboard/pull/6/commits/6f9ee0b5cd18437cc72d5037ebb7ffb55d395a6b

2023-05-30 12:04 UTC, Julian-Marco commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
Hier etwas schwierig, weil die Klasse nicht ngOnInit implementiert. Es gibt lediglich die onTransfers()-Methode, aber da funktioniert es nicht, weil die Methode erst nach dem Klicken des Transfer-Buttons getriggered wird. Es wäre aber schön, wenn man die storageUrl prefillen könnte. Soll hier auch ngOnInit implementiert werden?

2023-05-30 12:04 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
Fixed.

2023-05-30 12:09 UTC, Julian-Marco commented on src/modules/edc-demo/pages/contract-viewer/contract-viewer.component.ts
> +      this.authenticationService.userProfile$.subscribe(userProfile => {
Sicher? Das habe ich aus dem platform-frontend authentication service übernommen. Also falls das falsch ist, müsste es in beiden repos gefixed werden.

2023-05-30 12:14 UTC, Julian-Marco commented on src/modules/app/components/navigation/navigation.component.ts
> +      this.profile = userProfile
Fixed.

2023-05-30 12:36 UTC, marcelruland commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.html
> +<!--  <mat-form-field class="form-field" color="accent" id="form-field-destination">
Fair point!

2023-05-30 12:40 UTC, marcelruland commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
> Soll hier auch ngOnInit implementiert werden?

Jap!

2023-05-30 12:44 UTC, marcelruland commented on src/modules/edc-demo/pages/frame/context-switcher/context-switcher.component.ts
>    platformForm = new FormControl();
Ich meine Zeile 12 `platformForm = new FormControl();`.

2023-05-30 12:52 UTC, Julian-Marco commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.html
> +<!--  <mat-form-field class="form-field" color="accent" id="form-field-destination">
Done. https://github.com/agri-gaia/DataDashboard/pull/6/commits/9c53a2f3c0ba400aef50b4cf25d44f9d2a154d81

2023-05-30 12:58 UTC, Julian-Marco commented on src/modules/edc-demo/components/catalog-browser-transfer-dialog/catalog-browser-transfer-dialog.component.ts
> +    this.authenticationService.userProfile$.subscribe(userProfile => {
Done. https://github.com/agri-gaia/DataDashboard/pull/6/commits/014c9dd9f52feeec630a8dcf7d0aa7c3ab0e8f7c

2023-05-30 13:00 UTC, marcelruland commented on src/modules/app/app-config.service.ts
[Die Zeile](https://github.com/agri-gaia/DataDashboard/blob/feature/58533_keycloak/src/modules/edc-demo/services/edc-context.service.ts#LL2C1-L2C1) meine ich.

2023-05-30 13:03 UTC, Julian-Marco commented on src/modules/edc-demo/pages/frame/context-switcher/context-switcher.component.ts
>    platformForm = new FormControl();
Ich Trottel. Falsch verstanden. Done. https://github.com/agri-gaia/DataDashboard/pull/6/commits/16d76782d7cc38999c66e76996f5c314a2178a93

2023-05-30 13:06 UTC, Julian-Marco commented on src/modules/app/app-config.service.ts
Ah, jetzt gesehen. Komisch, dass VSC da keinen Error bei mir geschmissen hat. Allerdings scheint die komplette Datei keine Funktion mehr zu erfüllen? Ist erstmal raus: https://github.com/agri-gaia/DataDashboard/pull/6/commits/2057f42fb7f3432c1500076d25e3df1f71a88c99

2023-05-30 13:11 UTC, marcelruland commented on src/modules/edc-demo/pages/frame/context-switcher/context-switcher.component.html
Die Komponente wird nur in `src/modules/edc-demo/edc-demo.module.ts` deklariert, aber nirgends verwendet.

2023-05-30 13:15 UTC, marcelruland approved these changes

2023-05-30 13:16 UTC, Julian-Marco commented on src/modules/edc-demo/pages/frame/context-switcher/context-switcher.component.html
Ah, jo, sah schlimmer aus als es war. Done. https://github.com/agri-gaia/DataDashboard/pull/6/commits/ff80a8e8ed8534f35936a0ecd4b014647cfd4fe1

2023-05-31 06:53 UTC, marcelruland requested changes
.

2023-06-05 07:37 UTC, marcelruland approved these changes

2023-06-05 07:43 UTC, merged